version: "3"

services:

    attacker:
        image: handsonsecurity/seed-ubuntu:large
        container_name: seed-attacker
        tty: true
        cap_add:
                - ALL
        privileged: true
        volumes:
                - ./volumes:/volumes
        #network_mode: host
        networks:
            net-10.9.0.0:
                ipv4_address: 10.9.0.105


    Victim:
        image: jlesage/firefox
        restart: always
        container_name: victim-10.9.0.5
        volumes:
            - /dev/shm:/dev/shm
            #- ./volumes-victim:/volumes
        ports:
            - "5800:5800"
        #image: handsonsecurity/seed-ubuntu:large
        tty: true
        cap_add:
                - ALL
        privileged: true
        sysctls:
                - net.ipv4.ip_forward=1
        networks:
            net-10.9.0.0:
                ipv4_address: 10.9.0.5

        #command: bash -c "
        #              /etc/init.d/openbsd-inetd start  &&
        #              tail -f /dev/null
        #         "
                  
    User1:
        image: handsonsecurity/seed-ubuntu:large
        container_name: user1-10.9.0.6
        tty: true
        cap_add:
                - ALL
        volumes:
                - ./volumes-user1:/volumes
        networks:
            net-10.9.0.0:
                ipv4_address: 10.9.0.6

        command: bash -c "
                      /etc/init.d/openbsd-inetd start  &&
                      tail -f /dev/null
                 "

networks:
    net-10.9.0.0:
        name: net-10.9.0.0
        ipam:
            config:
                - subnet: 10.9.0.0/24
